### ISSUE TITLE
Drop `findByIdAndUpdate`

### ISSUE THREAD

**Issue by GA-MEB** [ga-wdi-boston/mongoose-crud#14]
Instead, have students do the following:

```
Thing.findById(id)
    .then(thing => {
      thing[field] = value;
      return thing.save();
    })
    .then(thing => console.log(thing.toJSON()))
    .catch(console.error);
```

Do not use `findByIdAndUpdate`, because that prevents you from implementing a lot of things.
Also be careful to mention that `update` does not pass along the modified document.

**Comment by raq929** [comment]
This issue has been resolved in this repo.
