### ISSUE TITLE
use `models` not `lib` to hold models

### ISSUE THREAD

**Issue by gaand** [ga-wdi-boston/mongoose-crud#3]
Map command line app to controller.

**Comment by MattB-GA-Boston** [comment]
Addressed this in 08e432a; please close if satisfactory.

**Comment by gaand** [comment]
@MattB-GA-Boston `master` has `models/person-finished.js`, should this be `solution:models/person.js`?

**Comment by MattB-GA-Boston** [comment]
@gaand yes, it should; I didn't have a chance to move it before I needed to deliver the lesson. I'll open a new issue for that right now.

Has this issue otherwise been resolved?

**Comment by raq929** [comment]
I believe this issue was resolved when #17 was closed.
