### ISSUE TITLE
It is no longer necessary to call `exec()` on a query to get a promise.

### ISSUE THREAD

**Issue by gaand** [ga-wdi-boston/mongoose-crud#7]
They added `then` to query which internally invokes an `exec().then()` chain.

See the code under the second [Query#then](http://mongoosejs.com/docs/api.html#query_Query-then) entry.

**Comment by MattB-GA-Boston** [comment]
Addressed this in 7aa0100; please close if satisfactory.

**Comment by gaand** [comment]
Thanks @MattB-GA-Boston
